$(document).ready(function(){$(window).width();var c=window.innerHeight,d=$(".default-header").height();$(".site-header.static").outerHeight();d=c-d;$(".fullscreen").css("height",c);$(".fitscreen").css("height",d);$(function(){$(".date-picker").datepicker()});document.getElementById("default-select")&&$("select").niceSelect();document.getElementById("default-select2")&&$("select").niceSelect();document.getElementById("service-select")&&$("select").niceSelect();$(".img-gal").magnificPopup({type:"image",
gallery:{enabled:!0}});$(".play-btn").magnificPopup({type:"image",mainClass:"mfp-fade",preloader:!1});$(".map-gal").magnificPopup({type:"image",gallery:{enabled:!0}});$(".mpa").magnificPopup({type:"image",gallery:{enabled:!0}});$(".nav-menu").superfish({animation:{opacity:"show"},speed:400});$(".active-hot-deal-carusel").owlCarousel({items:1,loop:!0,autoplay:!0,autoplayHoverPause:!0,smartSpeed:500,margin:30,dots:!0});$(".active-testimonial").owlCarousel({items:2,loop:!0,margin:30,autoplayHoverPause:!0,
smartSpeed:500,dots:!0,autoplay:!0,responsive:{0:{items:1},480:{items:1},992:{items:2}}});$(".active-recent-blog-carusel").owlCarousel({items:3,loop:!0,margin:30,dots:!0,autoplayHoverPause:!0,smartSpeed:500,autoplay:!0,responsive:{0:{items:1},480:{items:1},768:{items:2},961:{items:3}}});$("#nav-menu-container").length?(c=$("#nav-menu-container").clone().prop({id:"mobile-nav"}),c.find("> ul").attr({"class":"",id:""}),$("body .main-menu").append(c),$("body .main-menu").prepend('<button type="button" id="mobile-nav-toggle"><i class="lnr lnr-menu"></i></button>'),
$("body .main-menu").append('<div id="mobile-body-overly"></div>'),$("#mobile-nav").find(".menu-has-children").prepend('<i class="lnr lnr-chevron-down"></i>'),$(document).on("click",".menu-has-children i",function(a){$(this).next().toggleClass("menu-item-active");$(this).nextAll("ul").eq(0).slideToggle();$(this).toggleClass("lnr-chevron-up lnr-chevron-down")}),$(document).on("click","#mobile-nav-toggle",function(a){$("body").toggleClass("mobile-nav-active");$("#mobile-nav-toggle i").toggleClass("lnr-cross lnr-menu");
$("#mobile-body-overly").toggle()}),$(document).on("click",function(a){var b=$("#mobile-nav, #mobile-nav-toggle");!b.is(a.target)&&0===b.has(a.target).length&&$("body").hasClass("mobile-nav-active")&&($("body").removeClass("mobile-nav-active"),$("#mobile-nav-toggle i").toggleClass("lnr-cross lnr-menu"),$("#mobile-body-overly").fadeOut())})):$("#mobile-nav, #mobile-nav-toggle").length&&$("#mobile-nav, #mobile-nav-toggle").hide();$(".nav-menu a, #mobile-nav a, .scrollto").on("click",function(){if(location.pathname.replace(/^\//,
"")==this.pathname.replace(/^\//,"")&&location.hostname==this.hostname){var a=$(this.hash);if(a.length){var b=0;$("#header").length&&(b=$("#header").outerHeight(),$("#header").hasClass("header-fixed"));$("html, body").animate({scrollTop:a.offset().top-b},1500,"easeInOutExpo");$(this).parents(".nav-menu").length&&($(".nav-menu .menu-active").removeClass("menu-active"),$(this).closest("li").addClass("menu-active"));$("body").hasClass("mobile-nav-active")&&($("body").removeClass("mobile-nav-active"),
$("#mobile-nav-toggle i").toggleClass("lnr-times lnr-bars"),$("#mobile-body-overly").fadeOut());return!1}}});$(document).ready(function(){$("html, body").hide();window.location.hash?setTimeout(function(){$("html, body").scrollTop(0).show();$("html, body").animate({scrollTop:$(window.location.hash).offset().top-108},1E3)},0):$("html, body").show()});jQuery(document).ready(function(a){var b=window.location.pathname.split("/").pop();""==b&&(b="index.html");a('nav a[href="'+b+'"]').addClass("menu-active")});
$(document).ready(function(){$(".menu-has-children ul>li a").hasClass("menu-active")&&$(".menu-active").closest("ul").parentsUntil("a").addClass("parent-active")});$(window).scroll(function(){100<$(this).scrollTop()?$("#header").addClass("header-scrolled"):$("#header").removeClass("header-scrolled")});document.getElementById("map")&&google.maps.event.addDomListener(window,"load",function(){var a={zoom:11,center:new google.maps.LatLng(40.67,-73.94),styles:[{featureType:"water",elementType:"geometry",
stylers:[{color:"#e9e9e9"},{lightness:17}]},{featureType:"landscape",elementType:"geometry",stylers:[{color:"#f5f5f5"},{lightness:20}]},{featureType:"road.highway",elementType:"geometry.fill",stylers:[{color:"#ffffff"},{lightness:17}]},{featureType:"road.highway",elementType:"geometry.stroke",stylers:[{color:"#ffffff"},{lightness:29},{weight:.2}]},{featureType:"road.arterial",elementType:"geometry",stylers:[{color:"#ffffff"},{lightness:18}]},{featureType:"road.local",elementType:"geometry",stylers:[{color:"#ffffff"},
{lightness:16}]},{featureType:"poi",elementType:"geometry",stylers:[{color:"#f5f5f5"},{lightness:21}]},{featureType:"poi.park",elementType:"geometry",stylers:[{color:"#dedede"},{lightness:21}]},{elementType:"labels.text.stroke",stylers:[{visibility:"on"},{color:"#ffffff"},{lightness:16}]},{elementType:"labels.text.fill",stylers:[{saturation:36},{color:"#333333"},{lightness:40}]},{elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"geometry",stylers:[{color:"#f2f2f2"},
{lightness:19}]},{featureType:"administrative",elementType:"geometry.fill",stylers:[{color:"#fefefe"},{lightness:20}]},{featureType:"administrative",elementType:"geometry.stroke",stylers:[{color:"#fefefe"},{lightness:17},{weight:1.2}]}]},b=document.getElementById("map");a=new google.maps.Map(b,a);new google.maps.Marker({position:new google.maps.LatLng(40.67,-73.94),map:a,title:"Snazzy!"})});$(".active-blog-slider").owlCarousel({loop:!0,dots:!0,items:1,autoplay:!0,autoplayTimeout:2E3,smartSpeed:1E3,
animateOut:"fadeOut"});jQuery(document).ready(function(){jQuery("#gallery").unitegallery()});$(document).ready(function(){$("#mc_embed_signup").find("form").ajaxChimp()})});